[package]
name = "slave_bin"
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
