[package]
name = "slaveapi"
version.workspace = true
edition.workspace = true
authors.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
bytes = "1.7.1"
tokio-util = "0.7.12"
